### ISSUE TITLE
How can I use this script

### ISSUE THREAD

**Issue by tylor-e** [adamhwang/wheretocredit-calculator-xp#1]
I installed the script inTampermonkey in chrome, but nothing happened. Could you tell me the right way?

**Comment by adamhwang** [comment]
After installing Tampermoneky, simply navigate to https://github.com/adamhwang/wheretocredit-calculator-xp/raw/master/wheretocredit-calculator-xp.user.js and click Install.

I updated the readme with installation instructions.
