### ISSUE TITLE
Filters issue on Expedia

### ISSUE THREAD

**Issue by LacMajeur** [adamhwang/wheretocredit-calculator-xp#2]
Many thanks for this extension, it is very helpful! 

I suggest a way to improve it, if possible.

Example: Search on Expedia.
The result will be sorted by price ascending, and the miles will be correctly displayed on the side.

But if we decide to sort by flight duration, or to apply filters (stops, etc.), the miles are no longer displayed. 

If we reload the page, the miles come back, but without filters, and sorted by price ascending only.

IS there a way to change this?

Thanks a lot!

**Comment by adamhwang** [comment]
Thanks for the feedback @LacMajeur! I've fixed paging and sorting in both the greasemonkey script and the Chrome extension.
